name: Build Docker Images

on: [workflow_dispatch]

env:
  TUTOR_VERSION: 17.0.4
  S3_PLUGIN_VERSION: v1.4.0
  HDRUKFUTURESTHEME_PLUGIN_VERSION: v1.2.0-beta
  HDRUKSETTINGS_PLUGIN_VERSION: main
  EDX_PLATFORM_VERSION: hdruk/v1.2.0-beta

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Set up Python virtual environment
      run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VENV_ENVIRONMENT_NAME=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: Install Tutor
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        pip install "tutor[$TUTOR_VERSION]"

    - name: Install S3 plugin
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        pip install git+https://github.com/hastexo/tutor-contrib-s3@$S3_PLUGIN_VERSION

    - name: Install HDR UK Theme plugin
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        pip install git+https://github.com/evtdigital-hdruk/tutor-hdrukfuturestheme@$HDRUKFUTURESTHEME_PLUGIN_VERSION

    - name: Install HDR UK Settings plugin
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        pip install git+https://${{ secrets.USERNAME }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/evtdigital-hdruk/tutor-contrib-hdrukplugin.git@$HDRUKSETTINGS_PLUGIN_VERSION

    - name: Disable Indigo plugin
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor plugins disable indigo

    - name: Update plugins
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor config save
        tutor plugins update

    - name: Install additional Tutor plugins
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor plugins install discovery ecommerce cairn

    - name: Enable Installed Plugins
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor plugins enable s3 hdrukfuturestheme hdrukplugin discovery ecommerce cairn

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update Tutor Docker Registry
      run: |
        tutor config save --set DOCKER_REGISTRY=${{ secrets.ECR_REPOSITORY_URI }}/ --set DOCKER_IMAGE_OPENEDX=${{ secrets.ECR_REPOSITORY_URI }}/evtdigitalhdruk/openedx:$TUTOR_VERSION --set MFE_DOCKER_IMAGE=${{ secrets.ECR_REPOSITORY_URI }}/evtdigitalhdruk/openedx-mfe:$TUTOR_VERSION

    - name: Build Custom Open edX Image
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/evtdigital-hdruk/edx-platform.git --build-arg EDX_PLATFORM_VERSION=$EDX_PLATFORM_VERSION

    - name: Push Open edX Image to ECR
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor images push openedx

    - name: Prune Docker and Reclaim Disk Space
      run: |
        docker buildx prune -f
        docker system prune -fa

    - name: Build Custom MFE Image
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        touch maxparallelbuildkit.toml
        echo '[worker.oci]' > maxparallelbuildkit.toml
        echo 'max-parallelism = 2' >> maxparallelbuildkit.toml
        docker buildx create --use --name=maxpara2 --driver=docker-container --config=./maxparallelbuildkit.toml
        tutor images build mfe

    - name: Push MFE Image to ECR
      run: |
        source $VENV_ENVIRONMENT_NAME/bin/activate
        tutor images push mfe